// UiStage.ets — feat_heavy 生成组件选择器（勿手改）

import { Uicomp0000 } from './UicompSet000';
import { Uicomp0001 } from './UicompSet000';
import { Uicomp0002 } from './UicompSet001';
import { Uicomp0003 } from './UicompSet001';
import { Uicomp0004 } from './UicompSet002';
import { Uicomp0005 } from './UicompSet002';
import { Uicomp0006 } from './UicompSet003';
import { Uicomp0007 } from './UicompSet003';
import { Uicomp0008 } from './UicompSet004';
import { Uicomp0009 } from './UicompSet004';
import { Uicomp0010 } from './UicompSet005';
import { Uicomp0011 } from './UicompSet005';
import { Uicomp0012 } from './UicompSet006';
import { Uicomp0013 } from './UicompSet006';
import { Uicomp0014 } from './UicompSet007';
import { Uicomp0015 } from './UicompSet007';
import { Uicomp0016 } from './UicompSet008';
import { Uicomp0017 } from './UicompSet008';
import { Uicomp0018 } from './UicompSet009';
import { Uicomp0019 } from './UicompSet009';
import { Uicomp0020 } from './UicompSet010';
import { Uicomp0021 } from './UicompSet010';
import { Uicomp0022 } from './UicompSet011';
import { Uicomp0023 } from './UicompSet011';
import { Uicomp0024 } from './UicompSet012';
import { Uicomp0025 } from './UicompSet012';
import { Uicomp0026 } from './UicompSet013';
import { Uicomp0027 } from './UicompSet013';
import { Uicomp0028 } from './UicompSet014';
import { Uicomp0029 } from './UicompSet014';
import { Uicomp0030 } from './UicompSet015';
import { Uicomp0031 } from './UicompSet015';
import { Uicomp0032 } from './UicompSet016';
import { Uicomp0033 } from './UicompSet016';
import { Uicomp0034 } from './UicompSet017';
import { Uicomp0035 } from './UicompSet017';
import { Uicomp0036 } from './UicompSet018';
import { Uicomp0037 } from './UicompSet018';
import { Uicomp0038 } from './UicompSet019';
import { Uicomp0039 } from './UicompSet019';
import { Uicomp0040 } from './UicompSet020';
import { Uicomp0041 } from './UicompSet020';
import { Uicomp0042 } from './UicompSet021';
import { Uicomp0043 } from './UicompSet021';
import { Uicomp0044 } from './UicompSet022';
import { Uicomp0045 } from './UicompSet022';
import { Uicomp0046 } from './UicompSet023';
import { Uicomp0047 } from './UicompSet023';
import { Uicomp0048 } from './UicompSet024';
import { Uicomp0049 } from './UicompSet024';
import { Uicomp0050 } from './UicompSet025';
import { Uicomp0051 } from './UicompSet025';
import { Uicomp0052 } from './UicompSet026';
import { Uicomp0053 } from './UicompSet026';
import { Uicomp0054 } from './UicompSet027';
import { Uicomp0055 } from './UicompSet027';
import { Uicomp0056 } from './UicompSet028';
import { Uicomp0057 } from './UicompSet028';
import { Uicomp0058 } from './UicompSet029';
import { Uicomp0059 } from './UicompSet029';
import { Uicomp0060 } from './UicompSet030';
import { Uicomp0061 } from './UicompSet030';
import { Uicomp0062 } from './UicompSet031';
import { Uicomp0063 } from './UicompSet031';
import { Uicomp0064 } from './UicompSet032';
import { Uicomp0065 } from './UicompSet032';
import { Uicomp0066 } from './UicompSet033';
import { Uicomp0067 } from './UicompSet033';
import { Uicomp0068 } from './UicompSet034';
import { Uicomp0069 } from './UicompSet034';
import { Uicomp0070 } from './UicompSet035';
import { Uicomp0071 } from './UicompSet035';
import { Uicomp0072 } from './UicompSet036';
import { Uicomp0073 } from './UicompSet036';
import { Uicomp0074 } from './UicompSet037';
import { Uicomp0075 } from './UicompSet037';
import { Uicomp0076 } from './UicompSet038';
import { Uicomp0077 } from './UicompSet038';
import { Uicomp0078 } from './UicompSet039';
import { Uicomp0079 } from './UicompSet039';
import { Uicomp0080 } from './UicompSet040';
import { Uicomp0081 } from './UicompSet040';
import { Uicomp0082 } from './UicompSet041';
import { Uicomp0083 } from './UicompSet041';
import { Uicomp0084 } from './UicompSet042';
import { Uicomp0085 } from './UicompSet042';
import { Uicomp0086 } from './UicompSet043';
import { Uicomp0087 } from './UicompSet043';
import { Uicomp0088 } from './UicompSet044';
import { Uicomp0089 } from './UicompSet044';
import { Uicomp0090 } from './UicompSet045';
import { Uicomp0091 } from './UicompSet045';
import { Uicomp0092 } from './UicompSet046';
import { Uicomp0093 } from './UicompSet046';
import { Uicomp0094 } from './UicompSet047';
import { Uicomp0095 } from './UicompSet047';
import { Uicomp0096 } from './UicompSet048';
import { Uicomp0097 } from './UicompSet048';
import { Uicomp0098 } from './UicompSet049';
import { Uicomp0099 } from './UicompSet049';
import { Uicomp0100 } from './UicompSet050';
import { Uicomp0101 } from './UicompSet050';
import { Uicomp0102 } from './UicompSet051';
import { Uicomp0103 } from './UicompSet051';
import { Uicomp0104 } from './UicompSet052';
import { Uicomp0105 } from './UicompSet052';
import { Uicomp0106 } from './UicompSet053';
import { Uicomp0107 } from './UicompSet053';
import { Uicomp0108 } from './UicompSet054';
import { Uicomp0109 } from './UicompSet054';
import { Uicomp0110 } from './UicompSet055';
import { Uicomp0111 } from './UicompSet055';
import { Uicomp0112 } from './UicompSet056';
import { Uicomp0113 } from './UicompSet056';
import { Uicomp0114 } from './UicompSet057';
import { Uicomp0115 } from './UicompSet057';
import { Uicomp0116 } from './UicompSet058';
import { Uicomp0117 } from './UicompSet058';
import { Uicomp0118 } from './UicompSet059';
import { Uicomp0119 } from './UicompSet059';
import { Uicomp0120 } from './UicompSet060';
import { Uicomp0121 } from './UicompSet060';
import { Uicomp0122 } from './UicompSet061';
import { Uicomp0123 } from './UicompSet061';
import { Uicomp0124 } from './UicompSet062';
import { Uicomp0125 } from './UicompSet062';
import { Uicomp0126 } from './UicompSet063';
import { Uicomp0127 } from './UicompSet063';
import { Uicomp0128 } from './UicompSet064';
import { Uicomp0129 } from './UicompSet064';
import { Uicomp0130 } from './UicompSet065';
import { Uicomp0131 } from './UicompSet065';
import { Uicomp0132 } from './UicompSet066';
import { Uicomp0133 } from './UicompSet066';
import { Uicomp0134 } from './UicompSet067';
import { Uicomp0135 } from './UicompSet067';
import { Uicomp0136 } from './UicompSet068';
import { Uicomp0137 } from './UicompSet068';
import { Uicomp0138 } from './UicompSet069';
import { Uicomp0139 } from './UicompSet069';
import { Uicomp0140 } from './UicompSet070';
import { Uicomp0141 } from './UicompSet070';
import { Uicomp0142 } from './UicompSet071';
import { Uicomp0143 } from './UicompSet071';
import { Uicomp0144 } from './UicompSet072';
import { Uicomp0145 } from './UicompSet072';
import { Uicomp0146 } from './UicompSet073';
import { Uicomp0147 } from './UicompSet073';
import { Uicomp0148 } from './UicompSet074';
import { Uicomp0149 } from './UicompSet074';
import { Uicomp0150 } from './UicompSet075';
import { Uicomp0151 } from './UicompSet075';
import { Uicomp0152 } from './UicompSet076';
import { Uicomp0153 } from './UicompSet076';
import { Uicomp0154 } from './UicompSet077';
import { Uicomp0155 } from './UicompSet077';
import { Uicomp0156 } from './UicompSet078';
import { Uicomp0157 } from './UicompSet078';
import { Uicomp0158 } from './UicompSet079';
import { Uicomp0159 } from './UicompSet079';
import { Uicomp0160 } from './UicompSet080';
import { Uicomp0161 } from './UicompSet080';
import { Uicomp0162 } from './UicompSet081';
import { Uicomp0163 } from './UicompSet081';
import { Uicomp0164 } from './UicompSet082';
import { Uicomp0165 } from './UicompSet082';
import { Uicomp0166 } from './UicompSet083';
import { Uicomp0167 } from './UicompSet083';
import { Uicomp0168 } from './UicompSet084';
import { Uicomp0169 } from './UicompSet084';
import { Uicomp0170 } from './UicompSet085';
import { Uicomp0171 } from './UicompSet085';
import { Uicomp0172 } from './UicompSet086';
import { Uicomp0173 } from './UicompSet086';
import { Uicomp0174 } from './UicompSet087';
import { Uicomp0175 } from './UicompSet087';
import { Uicomp0176 } from './UicompSet088';
import { Uicomp0177 } from './UicompSet088';
import { Uicomp0178 } from './UicompSet089';
import { Uicomp0179 } from './UicompSet089';
import { Uicomp0180 } from './UicompSet090';
import { Uicomp0181 } from './UicompSet090';
import { Uicomp0182 } from './UicompSet091';
import { Uicomp0183 } from './UicompSet091';
import { Uicomp0184 } from './UicompSet092';
import { Uicomp0185 } from './UicompSet092';
import { Uicomp0186 } from './UicompSet093';
import { Uicomp0187 } from './UicompSet093';
import { Uicomp0188 } from './UicompSet094';
import { Uicomp0189 } from './UicompSet094';
import { Uicomp0190 } from './UicompSet095';
import { Uicomp0191 } from './UicompSet095';
import { Uicomp0192 } from './UicompSet096';
import { Uicomp0193 } from './UicompSet096';
import { Uicomp0194 } from './UicompSet097';
import { Uicomp0195 } from './UicompSet097';
import { Uicomp0196 } from './UicompSet098';
import { Uicomp0197 } from './UicompSet098';
import { Uicomp0198 } from './UicompSet099';
import { Uicomp0199 } from './UicompSet099';
import { Uicomp0200 } from './UicompSet100';
import { Uicomp0201 } from './UicompSet100';
import { Uicomp0202 } from './UicompSet101';
import { Uicomp0203 } from './UicompSet101';
import { Uicomp0204 } from './UicompSet102';
import { Uicomp0205 } from './UicompSet102';
import { Uicomp0206 } from './UicompSet103';
import { Uicomp0207 } from './UicompSet103';
import { Uicomp0208 } from './UicompSet104';
import { Uicomp0209 } from './UicompSet104';
import { Uicomp0210 } from './UicompSet105';
import { Uicomp0211 } from './UicompSet105';
import { Uicomp0212 } from './UicompSet106';
import { Uicomp0213 } from './UicompSet106';
import { Uicomp0214 } from './UicompSet107';
import { Uicomp0215 } from './UicompSet107';
import { Uicomp0216 } from './UicompSet108';
import { Uicomp0217 } from './UicompSet108';
import { Uicomp0218 } from './UicompSet109';
import { Uicomp0219 } from './UicompSet109';
import { Uicomp0220 } from './UicompSet110';
import { Uicomp0221 } from './UicompSet110';
import { Uicomp0222 } from './UicompSet111';
import { Uicomp0223 } from './UicompSet111';
import { Uicomp0224 } from './UicompSet112';
import { Uicomp0225 } from './UicompSet112';
import { Uicomp0226 } from './UicompSet113';
import { Uicomp0227 } from './UicompSet113';
import { Uicomp0228 } from './UicompSet114';
import { Uicomp0229 } from './UicompSet114';
import { Uicomp0230 } from './UicompSet115';
import { Uicomp0231 } from './UicompSet115';
import { Uicomp0232 } from './UicompSet116';
import { Uicomp0233 } from './UicompSet116';
import { Uicomp0234 } from './UicompSet117';
import { Uicomp0235 } from './UicompSet117';
import { Uicomp0236 } from './UicompSet118';
import { Uicomp0237 } from './UicompSet118';
import { Uicomp0238 } from './UicompSet119';
import { Uicomp0239 } from './UicompSet119';

@Component
export struct UiStage {
  @Prop sel: number = 0;

  build() {
    Column() {
    if (this.sel === 0) { Uicomp0000() }
    else if (this.sel === 1) { Uicomp0001() }
    else if (this.sel === 2) { Uicomp0002() }
    else if (this.sel === 3) { Uicomp0003() }
    else if (this.sel === 4) { Uicomp0004() }
    else if (this.sel === 5) { Uicomp0005() }
    else if (this.sel === 6) { Uicomp0006() }
    else if (this.sel === 7) { Uicomp0007() }
    else if (this.sel === 8) { Uicomp0008() }
    else if (this.sel === 9) { Uicomp0009() }
    else if (this.sel === 10) { Uicomp0010() }
    else if (this.sel === 11) { Uicomp0011() }
    else if (this.sel === 12) { Uicomp0012() }
    else if (this.sel === 13) { Uicomp0013() }
    else if (this.sel === 14) { Uicomp0014() }
    else if (this.sel === 15) { Uicomp0015() }
    else if (this.sel === 16) { Uicomp0016() }
    else if (this.sel === 17) { Uicomp0017() }
    else if (this.sel === 18) { Uicomp0018() }
    else if (this.sel === 19) { Uicomp0019() }
    else if (this.sel === 20) { Uicomp0020() }
    else if (this.sel === 21) { Uicomp0021() }
    else if (this.sel === 22) { Uicomp0022() }
    else if (this.sel === 23) { Uicomp0023() }
    else if (this.sel === 24) { Uicomp0024() }
    else if (this.sel === 25) { Uicomp0025() }
    else if (this.sel === 26) { Uicomp0026() }
    else if (this.sel === 27) { Uicomp0027() }
    else if (this.sel === 28) { Uicomp0028() }
    else if (this.sel === 29) { Uicomp0029() }
    else if (this.sel === 30) { Uicomp0030() }
    else if (this.sel === 31) { Uicomp0031() }
    else if (this.sel === 32) { Uicomp0032() }
    else if (this.sel === 33) { Uicomp0033() }
    else if (this.sel === 34) { Uicomp0034() }
    else if (this.sel === 35) { Uicomp0035() }
    else if (this.sel === 36) { Uicomp0036() }
    else if (this.sel === 37) { Uicomp0037() }
    else if (this.sel === 38) { Uicomp0038() }
    else if (this.sel === 39) { Uicomp0039() }
    else if (this.sel === 40) { Uicomp0040() }
    else if (this.sel === 41) { Uicomp0041() }
    else if (this.sel === 42) { Uicomp0042() }
    else if (this.sel === 43) { Uicomp0043() }
    else if (this.sel === 44) { Uicomp0044() }
    else if (this.sel === 45) { Uicomp0045() }
    else if (this.sel === 46) { Uicomp0046() }
    else if (this.sel === 47) { Uicomp0047() }
    else if (this.sel === 48) { Uicomp0048() }
    else if (this.sel === 49) { Uicomp0049() }
    else if (this.sel === 50) { Uicomp0050() }
    else if (this.sel === 51) { Uicomp0051() }
    else if (this.sel === 52) { Uicomp0052() }
    else if (this.sel === 53) { Uicomp0053() }
    else if (this.sel === 54) { Uicomp0054() }
    else if (this.sel === 55) { Uicomp0055() }
    else if (this.sel === 56) { Uicomp0056() }
    else if (this.sel === 57) { Uicomp0057() }
    else if (this.sel === 58) { Uicomp0058() }
    else if (this.sel === 59) { Uicomp0059() }
    else if (this.sel === 60) { Uicomp0060() }
    else if (this.sel === 61) { Uicomp0061() }
    else if (this.sel === 62) { Uicomp0062() }
    else if (this.sel === 63) { Uicomp0063() }
    else if (this.sel === 64) { Uicomp0064() }
    else if (this.sel === 65) { Uicomp0065() }
    else if (this.sel === 66) { Uicomp0066() }
    else if (this.sel === 67) { Uicomp0067() }
    else if (this.sel === 68) { Uicomp0068() }
    else if (this.sel === 69) { Uicomp0069() }
    else if (this.sel === 70) { Uicomp0070() }
    else if (this.sel === 71) { Uicomp0071() }
    else if (this.sel === 72) { Uicomp0072() }
    else if (this.sel === 73) { Uicomp0073() }
    else if (this.sel === 74) { Uicomp0074() }
    else if (this.sel === 75) { Uicomp0075() }
    else if (this.sel === 76) { Uicomp0076() }
    else if (this.sel === 77) { Uicomp0077() }
    else if (this.sel === 78) { Uicomp0078() }
    else if (this.sel === 79) { Uicomp0079() }
    else if (this.sel === 80) { Uicomp0080() }
    else if (this.sel === 81) { Uicomp0081() }
    else if (this.sel === 82) { Uicomp0082() }
    else if (this.sel === 83) { Uicomp0083() }
    else if (this.sel === 84) { Uicomp0084() }
    else if (this.sel === 85) { Uicomp0085() }
    else if (this.sel === 86) { Uicomp0086() }
    else if (this.sel === 87) { Uicomp0087() }
    else if (this.sel === 88) { Uicomp0088() }
    else if (this.sel === 89) { Uicomp0089() }
    else if (this.sel === 90) { Uicomp0090() }
    else if (this.sel === 91) { Uicomp0091() }
    else if (this.sel === 92) { Uicomp0092() }
    else if (this.sel === 93) { Uicomp0093() }
    else if (this.sel === 94) { Uicomp0094() }
    else if (this.sel === 95) { Uicomp0095() }
    else if (this.sel === 96) { Uicomp0096() }
    else if (this.sel === 97) { Uicomp0097() }
    else if (this.sel === 98) { Uicomp0098() }
    else if (this.sel === 99) { Uicomp0099() }
    else if (this.sel === 100) { Uicomp0100() }
    else if (this.sel === 101) { Uicomp0101() }
    else if (this.sel === 102) { Uicomp0102() }
    else if (this.sel === 103) { Uicomp0103() }
    else if (this.sel === 104) { Uicomp0104() }
    else if (this.sel === 105) { Uicomp0105() }
    else if (this.sel === 106) { Uicomp0106() }
    else if (this.sel === 107) { Uicomp0107() }
    else if (this.sel === 108) { Uicomp0108() }
    else if (this.sel === 109) { Uicomp0109() }
    else if (this.sel === 110) { Uicomp0110() }
    else if (this.sel === 111) { Uicomp0111() }
    else if (this.sel === 112) { Uicomp0112() }
    else if (this.sel === 113) { Uicomp0113() }
    else if (this.sel === 114) { Uicomp0114() }
    else if (this.sel === 115) { Uicomp0115() }
    else if (this.sel === 116) { Uicomp0116() }
    else if (this.sel === 117) { Uicomp0117() }
    else if (this.sel === 118) { Uicomp0118() }
    else if (this.sel === 119) { Uicomp0119() }
    else if (this.sel === 120) { Uicomp0120() }
    else if (this.sel === 121) { Uicomp0121() }
    else if (this.sel === 122) { Uicomp0122() }
    else if (this.sel === 123) { Uicomp0123() }
    else if (this.sel === 124) { Uicomp0124() }
    else if (this.sel === 125) { Uicomp0125() }
    else if (this.sel === 126) { Uicomp0126() }
    else if (this.sel === 127) { Uicomp0127() }
    else if (this.sel === 128) { Uicomp0128() }
    else if (this.sel === 129) { Uicomp0129() }
    else if (this.sel === 130) { Uicomp0130() }
    else if (this.sel === 131) { Uicomp0131() }
    else if (this.sel === 132) { Uicomp0132() }
    else if (this.sel === 133) { Uicomp0133() }
    else if (this.sel === 134) { Uicomp0134() }
    else if (this.sel === 135) { Uicomp0135() }
    else if (this.sel === 136) { Uicomp0136() }
    else if (this.sel === 137) { Uicomp0137() }
    else if (this.sel === 138) { Uicomp0138() }
    else if (this.sel === 139) { Uicomp0139() }
    else if (this.sel === 140) { Uicomp0140() }
    else if (this.sel === 141) { Uicomp0141() }
    else if (this.sel === 142) { Uicomp0142() }
    else if (this.sel === 143) { Uicomp0143() }
    else if (this.sel === 144) { Uicomp0144() }
    else if (this.sel === 145) { Uicomp0145() }
    else if (this.sel === 146) { Uicomp0146() }
    else if (this.sel === 147) { Uicomp0147() }
    else if (this.sel === 148) { Uicomp0148() }
    else if (this.sel === 149) { Uicomp0149() }
    else if (this.sel === 150) { Uicomp0150() }
    else if (this.sel === 151) { Uicomp0151() }
    else if (this.sel === 152) { Uicomp0152() }
    else if (this.sel === 153) { Uicomp0153() }
    else if (this.sel === 154) { Uicomp0154() }
    else if (this.sel === 155) { Uicomp0155() }
    else if (this.sel === 156) { Uicomp0156() }
    else if (this.sel === 157) { Uicomp0157() }
    else if (this.sel === 158) { Uicomp0158() }
    else if (this.sel === 159) { Uicomp0159() }
    else if (this.sel === 160) { Uicomp0160() }
    else if (this.sel === 161) { Uicomp0161() }
    else if (this.sel === 162) { Uicomp0162() }
    else if (this.sel === 163) { Uicomp0163() }
    else if (this.sel === 164) { Uicomp0164() }
    else if (this.sel === 165) { Uicomp0165() }
    else if (this.sel === 166) { Uicomp0166() }
    else if (this.sel === 167) { Uicomp0167() }
    else if (this.sel === 168) { Uicomp0168() }
    else if (this.sel === 169) { Uicomp0169() }
    else if (this.sel === 170) { Uicomp0170() }
    else if (this.sel === 171) { Uicomp0171() }
    else if (this.sel === 172) { Uicomp0172() }
    else if (this.sel === 173) { Uicomp0173() }
    else if (this.sel === 174) { Uicomp0174() }
    else if (this.sel === 175) { Uicomp0175() }
    else if (this.sel === 176) { Uicomp0176() }
    else if (this.sel === 177) { Uicomp0177() }
    else if (this.sel === 178) { Uicomp0178() }
    else if (this.sel === 179) { Uicomp0179() }
    else if (this.sel === 180) { Uicomp0180() }
    else if (this.sel === 181) { Uicomp0181() }
    else if (this.sel === 182) { Uicomp0182() }
    else if (this.sel === 183) { Uicomp0183() }
    else if (this.sel === 184) { Uicomp0184() }
    else if (this.sel === 185) { Uicomp0185() }
    else if (this.sel === 186) { Uicomp0186() }
    else if (this.sel === 187) { Uicomp0187() }
    else if (this.sel === 188) { Uicomp0188() }
    else if (this.sel === 189) { Uicomp0189() }
    else if (this.sel === 190) { Uicomp0190() }
    else if (this.sel === 191) { Uicomp0191() }
    else if (this.sel === 192) { Uicomp0192() }
    else if (this.sel === 193) { Uicomp0193() }
    else if (this.sel === 194) { Uicomp0194() }
    else if (this.sel === 195) { Uicomp0195() }
    else if (this.sel === 196) { Uicomp0196() }
    else if (this.sel === 197) { Uicomp0197() }
    else if (this.sel === 198) { Uicomp0198() }
    else if (this.sel === 199) { Uicomp0199() }
    else if (this.sel === 200) { Uicomp0200() }
    else if (this.sel === 201) { Uicomp0201() }
    else if (this.sel === 202) { Uicomp0202() }
    else if (this.sel === 203) { Uicomp0203() }
    else if (this.sel === 204) { Uicomp0204() }
    else if (this.sel === 205) { Uicomp0205() }
    else if (this.sel === 206) { Uicomp0206() }
    else if (this.sel === 207) { Uicomp0207() }
    else if (this.sel === 208) { Uicomp0208() }
    else if (this.sel === 209) { Uicomp0209() }
    else if (this.sel === 210) { Uicomp0210() }
    else if (this.sel === 211) { Uicomp0211() }
    else if (this.sel === 212) { Uicomp0212() }
    else if (this.sel === 213) { Uicomp0213() }
    else if (this.sel === 214) { Uicomp0214() }
    else if (this.sel === 215) { Uicomp0215() }
    else if (this.sel === 216) { Uicomp0216() }
    else if (this.sel === 217) { Uicomp0217() }
    else if (this.sel === 218) { Uicomp0218() }
    else if (this.sel === 219) { Uicomp0219() }
    else if (this.sel === 220) { Uicomp0220() }
    else if (this.sel === 221) { Uicomp0221() }
    else if (this.sel === 222) { Uicomp0222() }
    else if (this.sel === 223) { Uicomp0223() }
    else if (this.sel === 224) { Uicomp0224() }
    else if (this.sel === 225) { Uicomp0225() }
    else if (this.sel === 226) { Uicomp0226() }
    else if (this.sel === 227) { Uicomp0227() }
    else if (this.sel === 228) { Uicomp0228() }
    else if (this.sel === 229) { Uicomp0229() }
    else if (this.sel === 230) { Uicomp0230() }
    else if (this.sel === 231) { Uicomp0231() }
    else if (this.sel === 232) { Uicomp0232() }
    else if (this.sel === 233) { Uicomp0233() }
    else if (this.sel === 234) { Uicomp0234() }
    else if (this.sel === 235) { Uicomp0235() }
    else if (this.sel === 236) { Uicomp0236() }
    else if (this.sel === 237) { Uicomp0237() }
    else if (this.sel === 238) { Uicomp0238() }
    else if (this.sel === 239) { Uicomp0239() }
    }
  }
}
